config/routes.rb
Rails.application.routes.draw do
  resources :characteristics

  resources :requirements

  resources :parts

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  has_many :requirements
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :discussable, polymorphic: true
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :requirements
  
  has_attached_file :print, :styles => { :printsize => "800x800", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to :part
  belongs_to :characteristic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1
  # PATCH/PUT /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic.destroy
    respond_to do |format|
      format.html { redirect_to characteristics_url, notice: 'Characteristic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def characteristic_params
      params.require(:characteristic).permit(:name, :symbol, :two_sided, :continuous)
    end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  
  def index
    @discussed = find_discussed
    @discussions = @discussed.discussions
  end
  
  def create
    @discussed = find_discussed
    @discussion = @discussed.discussions.new(discussion_params)
    if @discussion.save
      flash[:notice] = "Discussion Posted"
      redirect_to @discussed
    else
      render :action => 'new'
    end
  end
 
  private
  def discussion_params
    params.require(:discussion).permit(:body)
  end
  
  def find_discussed
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:name, :partnumber, :revision, :customer, :print)
    end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:show, :edit, :update, :destroy]

  # GET /requirements
  # GET /requirements.json
  def index
    @requirements = Requirement.all
  end

  # GET /requirements/1
  # GET /requirements/1.json
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements
  # POST /requirements.json
  def create
    @requirement = Requirement.new(requirement_params)

    respond_to do |format|
      if @requirement.save
        format.html { redirect_to @requirement, notice: 'Requirement was successfully created.' }
        format.json { render :show, status: :created, location: @requirement }
      else
        format.html { render :new }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requirements/1
  # PATCH/PUT /requirements/1.json
  def update
    respond_to do |format|
      if @requirement.update(requirement_params)
        format.html { redirect_to @requirement, notice: 'Requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @requirement }
      else
        format.html { render :edit }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1
  # DELETE /requirements/1.json
  def destroy
    @requirement.destroy
    respond_to do |format|
      format.html { redirect_to requirements_url, notice: 'Requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requirement_params
      params.require(:requirement).permit(:bubble, :dim, :tolerance_less, :tolerance_plus, :characteristic_id, :part_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/characteristics/_form.html.haml
= simple_form_for(@characteristic) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :symbol
    = f.input :two_sided
    = f.input :continuous

  .form-actions
    = f.button :submit

app/views/characteristics/edit.html.haml
%h1 Editing characteristic

= render 'form'

= link_to 'Show', @characteristic
\|
= link_to 'Back', characteristics_path

app/views/characteristics/index.html.haml
%h1 Listing characteristics

%table
  %tr
    %th Name
    %th Symbol
    %th Two sided
    %th Continuous
    %th
    %th
    %th

  - @characteristics.each do |characteristic|
    %tr
      %td= characteristic.name
      %td= characteristic.symbol
      %td= characteristic.two_sided
      %td= characteristic.continuous
      %td= link_to 'Show', characteristic
      %td= link_to 'Edit', edit_characteristic_path(characteristic)
      %td= link_to 'Destroy', characteristic, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Characteristic', new_characteristic_path

app/views/characteristics/new.html.haml
%h1 New characteristic

= render 'form'

= link_to 'Back', characteristics_path

app/views/characteristics/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @characteristic.name
%p
  %b Symbol:
  = @characteristic.symbol
%p
  %b Two sided:
  = @characteristic.two_sided
%p
  %b Continuous:
  = @characteristic.continuous

= link_to 'Edit', edit_characteristic_path(@characteristic)
\|
= link_to 'Back', characteristics_path

app/views/dim_types/_form.html.haml
= simple_form_for(@dim_type) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :symbol
    = f.input :two_sided
    = f.input :continuous

  .form-actions
    = f.button :submit

app/views/discussions/index.html.haml
#discussions-container
  - @discussions.each do |discussion|
    = discussion.body 
    %br

app/views/discussions/new.html.haml
= simple_form_for [@discussed, Discussion.new] do |f|
  = f.error_notification

  .form-inputs
    = f.input :body
    
  .form-actions
    = f.button :submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partvuze</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parts/_form.html.haml
= simple_form_for(@part) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :partnumber
    = f.input :revision
    = f.input :customer

  .form-actions
    = f.button :submit

app/views/parts/edit.html.haml
%h1 Editing part

= render 'form'

= link_to 'Show', @part
\|
= link_to 'Back', parts_path

app/views/parts/index.html.haml
%h1 Listing parts

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @parts.each do |part|
    %tr
      %td= part.name
      %td= link_to 'Show', part
      %td= link_to 'Edit', edit_part_path(part)
      %td= link_to 'Destroy', part, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Part', new_part_path

app/views/parts/new.html.haml
%h1 New part

= render 'form'

= link_to 'Back', parts_path

app/views/parts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @part.partnumber
  
%p
  %b Name:
  = @part.name
  
%p
  %b Name:
  = @part.revision

%p
  %b Name:
  = @part.customer

= link_to 'Edit', edit_part_path(@part)
\|
= link_to 'Back', parts_path
%br

%requirementcontainer
  -@part.requirements.each do |requirement|
    = div_for(requirement, class: "requirement-box") do
      .bubble= requirement.bubble
      .characteristic= requirement.characteristic.name
      .dimension= requirement.dim
      .toleranceup
        = precede "+ " do 
          =requirement.tolerance_plus
      .tolerancedn
        = precede "- " do 
          =requirement.tolerance_less

app/views/requirements/_form.html.haml
= simple_form_for(@requirement) do |f|
  = f.error_notification

  .form-inputs
    = f.association :part
    = f.input :bubble
    = f.association :characteristic
    = f.input :dim
    = f.input :tolerance_less
    = f.input :tolerance_plus

  .form-actions
    = f.button :submit

app/views/requirements/edit.html.haml
%h1 Editing requirement

= render 'form'

= link_to 'Show', @requirement
\|
= link_to 'Back', requirements_path

app/views/requirements/index.html.haml
%h1 Listing requirements

%table
  %tr
    %th Bubble
    %th Dim
    %th Tolerance less
    %th Tolerance plus
    %th Dim type
    %th Part
    %th
    %th
    %th

  - @requirements.each do |requirement|
    %tr
      %td= requirement.bubble
      %td= requirement.dim
      %td= requirement.tolerance_less
      %td= requirement.tolerance_plus
      %td= requirement.dim_type
      %td= requirement.part_id
      %td= link_to 'Show', requirement
      %td= link_to 'Edit', edit_requirement_path(requirement)
      %td= link_to 'Destroy', requirement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Requirement', new_requirement_path

app/views/requirements/new.html.haml
%h1 New requirement

= render 'form'

= link_to 'Back', requirements_path

app/views/requirements/show.html.haml
%p#notice= notice

%p
  %b Bubble:
  = @requirement.bubble
%p
  %b Dim:
  = @requirement.dim
%p
  %b Tolerance less:
  = @requirement.tolerance_less
%p
  %b Tolerance plus:
  = @requirement.tolerance_plus
%p
  %b Dim type:
  = @requirement.characteristic.name
%p
  %b Part:
  = @requirement.part.name

= link_to 'Edit', edit_requirement_path(@requirement)
\|
= link_to 'Back', requirements_path

= div_for(@requirement, class: "requirement-box") do
  .bubble= @requirement.bubble
  .characteristic= @requirement.characteristic.name
  .dimension= @requirement.dim
  .toleranceup
    +
    = @requirement.tolerance_plus
  .tolerancedn
    = precede "- " do 
      =@requirement.tolerance_less

  
  